# Generated by Django 2.1.5 on 2019-01-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('text_input', models.TextField()),
                ('daily_frequency', models.FloatField()),
                ('creation_time', models.DateTimeField()),
                ('special', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('weight', models.FloatField()),
                ('standing_hours', models.FloatField()),
                ('active_energy', models.FloatField()),
                ('resting_energy', models.FloatField()),
                ('exercise_minutes', models.FloatField()),
                ('flights_climbed', models.FloatField()),
                ('walking_heart_rate', models.FloatField()),
                ('resting_heart_rate', models.FloatField()),
                ('heart_rate_variability', models.FloatField()),
                ('sleep', models.FloatField()),
                ('estimated_sleep', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('anger', models.FloatField()),
                ('sadness', models.FloatField()),
                ('happiness', models.FloatField()),
                ('fear', models.FloatField()),
                ('disgust', models.FloatField()),
                ('stress', models.FloatField()),
                ('productivity', models.FloatField()),
                ('jounal_note', models.TextField()),
            ],
        ),
    ]
