# Generated by Django 2.1.5 on 2019-01-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kpi', models.FloatField()),
                ('journal', models.TextField(max_length=500)),
            ],
        ),
    ]
